name: tewari_say_cheese_pos
description: TEWARI SAY CHEESE POS - HOWRAH
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Printing & Bluetooth (may require platform permissions)
  flutter_bluetooth_printer: ^2.20.0

  # Local DB
  sqflite: ^2.2.0
  path: any

  # Utilities
  uuid: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
